# Generated by Django 3.1.2 on 2020-10-07 23:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('start_sales', models.DateField(blank=True)),
                ('end_sales', models.DateField(blank=True)),
                ('units', models.PositiveIntegerField()),
                ('soldout', models.BooleanField(default=False)),
                ('bakingdate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('deliverydate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('bakingtime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('Plain_sold', models.PositiveIntegerField(default=0)),
                ('Sesame_sold', models.PositiveIntegerField(default=0)),
                ('Salt_sold', models.PositiveIntegerField(default=0)),
                ('Onion_sold', models.PositiveIntegerField(default=0)),
                ('Poppy_sold', models.PositiveIntegerField(default=0)),
                ('Garlic_sold', models.PositiveIntegerField(default=0)),
                ('Everything_sold', models.PositiveIntegerField(default=0)),
                ('RandomBake', models.TextField(blank=True)),
                ('RandomBake_sold', models.PositiveIntegerField(default=0)),
                ('CreamCheese_sold', models.PositiveIntegerField(default=0)),
                ('Batch_Notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ActiveSales',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=50)),
                ('Last_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_Street1', models.CharField(blank=True, max_length=100)),
                ('delivery_Street2', models.CharField(blank=True, max_length=100)),
                ('delivery_City', models.CharField(blank=True, max_length=3)),
                ('delivery_State', models.CharField(blank=True, max_length=100)),
                ('delivery_Zip', models.CharField(blank=True, max_length=10)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('customer_Notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Featurette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('index', 'index'), ('About Us', 'About Us'), ('Sanitation Protocols', 'Sanitation'), ('Licenses', 'Licenses'), ('Projects', 'Projects')], max_length=35)),
                ('order', models.PositiveIntegerField(default=1)),
                ('subtitle', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, default='Description goes here.', max_length=430)),
                ('Story', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='highlight_images')),
                ('photo_alt', models.CharField(blank=True, max_length=25)),
                ('button', models.CharField(blank=True, max_length=18)),
                ('button_link', models.CharField(default='#', max_length=264)),
                ('button_class', models.CharField(default='btn btn-sm btn-outline-secondary', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, unique=True)),
                ('story', models.TextField(max_length=300)),
                ('script', models.TextField(default='None')),
                ('photo2', models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='highlight_images')),
                ('photo_alt', models.CharField(max_length=25)),
                ('button', models.CharField(max_length=18)),
                ('button_link', models.CharField(max_length=264)),
                ('button_class', models.CharField(default='index', max_length=264)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceid', models.CharField(default='null', max_length=14, unique=True)),
                ('Plain_sold', models.PositiveIntegerField(default=0)),
                ('Sesame_sold', models.PositiveIntegerField(default=0)),
                ('Salt_sold', models.PositiveIntegerField(default=0)),
                ('Onion_sold', models.PositiveIntegerField(default=0)),
                ('Poppy_sold', models.PositiveIntegerField(default=0)),
                ('Garlic_sold', models.PositiveIntegerField(default=0)),
                ('Everything_sold', models.PositiveIntegerField(default=0)),
                ('RandomBake_sold', models.PositiveIntegerField(default=0)),
                ('CreamCheese_sold', models.PositiveIntegerField(default=0)),
                ('deliveryinfo', models.TextField(blank=True)),
                ('cart', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.activesales')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ManyToManyField(related_name='features', to='MainPage.Featurette')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
