# Generated by Django 3.1.2 on 2020-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoiceid',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
