# Generated by Django 3.1.2 on 2020-10-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20201007_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='First_name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delivery_City',
            new_name='dCity',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delivery_State',
            new_name='dState',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delivery_Street1',
            new_name='dStreet1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delivery_Street2',
            new_name='dStreet2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delivery_Zip',
            new_name='dZip',
        ),
    ]
