# Generated by Django 3.1 on 2020-09-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_auto_20200902_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='baking_batch',
            fields=[
                ('batch_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('batch_date', models.DateField()),
                ('batch_type', models.CharField(max_length=100)),
                ('room_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('room_humid', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=264)),
                ('ingred_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingred_metric', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ShapingFinishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_each_item', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items_produced', models.PositiveIntegerField()),
                ('retard_started', models.TimeField()),
                ('retard_finished', models.TimeField()),
                ('preform_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('postform_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('boil_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('oven_first_temp', models.PositiveIntegerField()),
                ('oven_first_time', models.PositiveIntegerField()),
                ('oven_second_temp', models.PositiveIntegerField()),
                ('oven_second_time', models.PositiveIntegerField()),
                ('steam_used', models.BooleanField()),
                ('steam_time', models.PositiveIntegerField()),
                ('shaping_finishing_notes', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.baking_batch')),
            ],
        ),
        migrations.CreateModel(
            name='PreFerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchdate', models.DateField()),
                ('ferm_started', models.TimeField()),
                ('ferm_temp_start', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ferm_temp_fermented', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ferm_temp_after_retardation', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ferm_final_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ferm_notes', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.baking_batch')),
                ('ferm_ingredients', models.ManyToManyField(to='MainPage.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough_mixed_minutes', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_mixer_speed', models.PositiveIntegerField()),
                ('dough_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_final_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_mixer_spring', models.PositiveIntegerField()),
                ('knead_start_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_finish_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_final_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dough_notes', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.baking_batch')),
                ('dough_ingredients', models.ManyToManyField(to='MainPage.Ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='baking_batch',
            name='Dough',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.dough'),
        ),
        migrations.AddField(
            model_name='baking_batch',
            name='PreFerment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.preferment'),
        ),
        migrations.AddField(
            model_name='baking_batch',
            name='ShapingFinishing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.shapingfinishing'),
        ),
    ]
