# Generated by Django 3.1 on 2020-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_auto_20200910_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='baking_batch',
            name='batch_final_notes',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='baking_batch',
            name='batch_photo',
            field=models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images'),
        ),
        migrations.AddField(
            model_name='dough',
            name='dough_photo',
            field=models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images'),
        ),
        migrations.AddField(
            model_name='dough',
            name='kneading_photo',
            field=models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images'),
        ),
        migrations.AddField(
            model_name='shapingfinishing',
            name='baked_photo',
            field=models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images'),
        ),
        migrations.AddField(
            model_name='shapingfinishing',
            name='shape_photo',
            field=models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images'),
        ),
    ]
