# Generated by Django 3.1 on 2020-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_auto_20200910_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baking_batch',
            name='batch_final_notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='dough',
            name='dough_notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='preferment',
            name='ferm_notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='shapingfinishing',
            name='shaping_finishing_notes',
            field=models.TextField(default='None'),
        ),
    ]
