# Generated by Django 3.1.2 on 2020-10-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_auto_20201008_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Fame',
            new_name='Fname',
        ),
    ]
