# Generated by Django 3.1 on 2020-09-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_auto_20200910_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferment',
            name='batchdate',
        ),
    ]
