# Generated by Django 3.1.2 on 2020-10-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_auto_20201008_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Lname',
            field=models.CharField(max_length=50),
        ),
    ]
