# Generated by Django 3.1 on 2020-09-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_remove_preferment_batchdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSales',
            fields=[
                ('batch', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('start_sales', models.DateField()),
                ('end_sales', models.DateField()),
                ('units', models.PositiveIntegerField()),
                ('soldout', models.BooleanField(default=False)),
            ],
        ),
    ]
