# Generated by Django 3.1.2 on 2020-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_auto_20201008_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dCity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dState',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
