# Generated by Django 3.1 on 2020-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_activesales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='soldout',
            field=models.BooleanField(),
        ),
    ]
