# Generated by Django 3.1.2 on 2020-10-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_auto_20201008_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.activesales'),
        ),
    ]
