# Generated by Django 3.1.2 on 2020-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_auto_20201008_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='batch',
        ),
        migrations.AddField(
            model_name='orders',
            name='batch',
            field=models.ManyToManyField(to='MainPage.ActiveSales'),
        ),
    ]
