# Generated by Django 3.1 on 2020-09-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_auto_20200913_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='photo',
        ),
        migrations.AddField(
            model_name='highlight',
            name='script',
            field=models.TextField(default='None'),
        ),
    ]
