# Generated by Django 3.1 on 2020-09-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0013_auto_20200913_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='button_class',
            field=models.CharField(default='index', max_length=264),
        ),
    ]
