# Generated by Django 3.1 on 2020-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0015_featurette'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='subtitle',
            field=models.CharField(default='', max_length=35),
        ),
    ]
