# Generated by Django 3.1.2 on 2020-10-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0015_auto_20201008_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
