# Generated by Django 3.1 on 2020-09-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0016_featurette_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='description',
            field=models.TextField(default='Description goes here.', max_length=430),
        ),
    ]
