# Generated by Django 3.1 on 2020-09-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0017_auto_20200914_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurette',
            name='subtitle',
            field=models.CharField(default='', max_length=40),
        ),
    ]
