# Generated by Django 3.1 on 2020-09-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0019_auto_20200916_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baking_batch',
            name='Dough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.dough'),
        ),
        migrations.AlterField(
            model_name='baking_batch',
            name='PreFerment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.preferment'),
        ),
        migrations.AlterField(
            model_name='baking_batch',
            name='ShapingFinishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.shapingfinishing'),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='type',
            field=models.CharField(max_length=35),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ManyToManyField(related_name='features', to='MainPage.Featurette')),
            ],
        ),
    ]
