# Generated by Django 3.1.2 on 2020-10-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0019_auto_20201008_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
