# Generated by Django 3.1.2 on 2020-10-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0020_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceid', models.CharField(max_length=14, unique=True)),
                ('Plain_sold', models.PositiveIntegerField(default=0)),
                ('Sesame_sold', models.PositiveIntegerField(default=0)),
                ('Salt_sold', models.PositiveIntegerField(default=0)),
                ('Onion_sold', models.PositiveIntegerField(default=0)),
                ('Poppy_sold', models.PositiveIntegerField(default=0)),
                ('Garlic_sold', models.PositiveIntegerField(default=0)),
                ('Everything_sold', models.PositiveIntegerField(default=0)),
                ('RandomBake_sold', models.PositiveIntegerField(default=0)),
                ('CreamCheese_sold', models.PositiveIntegerField(default=0)),
                ('deliveryinfo', models.TextField(blank=True)),
                ('cart', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainPage.activesales')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.customer')),
            ],
        ),
    ]
