# Generated by Django 3.1 on 2020-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0021_auto_20200916_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurette',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='photo',
            field=models.ImageField(blank=True, upload_to='highlight_images'),
        ),
    ]
