# Generated by Django 3.1.2 on 2020-10-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0022_auto_20201008_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_batch', to='MainPage.activesales'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='MainPage.customer'),
        ),
    ]
