# Generated by Django 3.1.2 on 2020-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0023_auto_20201009_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
