# Generated by Django 3.1 on 2020-09-17 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0023_auto_20200916_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='highlight',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='description',
            field=models.TextField(blank=True, default='Description goes here.', max_length=430),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='type',
            field=models.CharField(choices=[('index page', 'index'), ('About Us', 'About Us'), ('Sanitaion', 'Sanitation Protocols'), ('Licenses', 'Licenses')], max_length=35),
        ),
    ]
