# Generated by Django 3.1 on 2020-09-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0024_auto_20200917_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dough',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='dough',
            name='dough_ingredients',
        ),
        migrations.RemoveField(
            model_name='preferment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='preferment',
            name='ferm_ingredients',
        ),
        migrations.RemoveField(
            model_name='shapingfinishing',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingred_amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingred_metric',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='button',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='button_class',
            field=models.CharField(default='btn btn-sm btn-outline-secondary', max_length=264),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='subtitle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='featurette',
            name='type',
            field=models.CharField(choices=[('index', 'index'), ('About Us', 'About Us'), ('Sanitation Protocols', 'Sanitation'), ('Licenses', 'Licenses'), ('Projects', 'Projects')], max_length=35),
        ),
        migrations.DeleteModel(
            name='baking_batch',
        ),
        migrations.DeleteModel(
            name='Dough',
        ),
        migrations.DeleteModel(
            name='PreFerment',
        ),
        migrations.DeleteModel(
            name='ShapingFinishing',
        ),
    ]
