# Generated by Django 3.1.2 on 2020-10-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0024_auto_20201020_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
