# Generated by Django 3.1.2 on 2020-10-29 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0025_auto_20201023_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
