# Generated by Django 3.1 on 2020-09-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0025_auto_20200920_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
