# Generated by Django 3.1 on 2020-09-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0026_delete_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesales',
            options={'verbose_name_plural': 'ActiveSales'},
        ),
    ]
