# Generated by Django 3.1 on 2020-09-25 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainPage', '0027_auto_20200921_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='CreamCheese_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Everything_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Garlic_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Onion_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Plain_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='RandomBake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activesales',
            name='RandomBake_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Salt_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='Sesame_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_City',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_State',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_Street1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_Street2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_Zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='eMail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plain_sold', models.PositiveIntegerField(default=0)),
                ('Sesame_sold', models.PositiveIntegerField(default=0)),
                ('Salt_sold', models.PositiveIntegerField(default=0)),
                ('Onion_sold', models.PositiveIntegerField(default=0)),
                ('Garlic_sold', models.PositiveIntegerField(default=0)),
                ('Everything_sold', models.PositiveIntegerField(default=0)),
                ('RandomBake_sold', models.PositiveIntegerField(default=0)),
                ('CreamCheese_sold', models.PositiveIntegerField(default=0)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainPage.activesales')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
