# Generated by Django 3.1.2 on 2020-10-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0028_auto_20201029_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.DateTimeField(blank=True),
        ),
    ]
