# Generated by Django 3.1 on 2020-09-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0028_auto_20200925_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='eMail',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Fname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='d_City',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
