# Generated by Django 3.1 on 2020-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0029_auto_20200925_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=50)),
                ('Lname', models.CharField(blank=True, max_length=50)),
                ('d_Street1', models.CharField(blank=True, max_length=100)),
                ('d_Street2', models.CharField(blank=True, max_length=100)),
                ('d_City', models.CharField(blank=True, max_length=3)),
                ('d_State', models.CharField(blank=True, max_length=100)),
                ('d_Zip', models.CharField(blank=True, max_length=10)),
                ('Phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='d_City',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='d_State',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='d_Street1',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='d_Street2',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='d_Zip',
        ),
    ]
