# Generated by Django 3.1.2 on 2020-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0030_auto_20201029_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailing_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='pref_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='rando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='emil_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='text_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
