# Generated by Django 3.1 on 2020-09-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0030_auto_20200925_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='Poppy_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='Poppy_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
