# Generated by Django 3.1.2 on 2020-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0031_auto_20201109_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
