# Generated by Django 3.1.2 on 2020-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0032_auto_20201109_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pref_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
