# Generated by Django 3.1 on 2020-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0032_auto_20200925_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='Batch_Notes',
            field=models.TextField(blank=True),
        ),
    ]
