# Generated by Django 3.1.2 on 2020-10-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0033_activesales_batch_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='soldout',
            field=models.BooleanField(),
        ),
    ]
