# Generated by Django 3.1.2 on 2020-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0033_auto_20201109_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dState',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
