# Generated by Django 3.1.2 on 2020-12-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0034_auto_20201110_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plain_sold', models.PositiveIntegerField(default=0)),
                ('Sesame_sold', models.PositiveIntegerField(default=0)),
                ('Salt_sold', models.PositiveIntegerField(default=0)),
                ('Onion_sold', models.PositiveIntegerField(default=0)),
                ('Poppy_sold', models.PositiveIntegerField(default=0)),
                ('Garlic_sold', models.PositiveIntegerField(default=0)),
                ('Everything_sold', models.PositiveIntegerField(default=0)),
                ('RandomBake_sold', models.PositiveIntegerField(default=0)),
                ('CreamCheese_sold', models.PositiveIntegerField(default=0)),
                ('deliveryinfo', models.TextField(blank=True)),
                ('cart', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='base_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_order', to='MainPage.subscription'),
        ),
    ]
