# Generated by Django 3.1.2 on 2020-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0034_auto_20201005_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activesales',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='batch',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='end_sales',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='start_sales',
            field=models.DateField(blank=True),
        ),
    ]
