# Generated by Django 3.1.2 on 2020-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0035_auto_20201201_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_descrip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
