# Generated by Django 3.1.2 on 2020-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0036_subscription_order_descrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='rando',
            new_name='friend',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mailing_list',
            field=models.BooleanField(default=True),
        ),
    ]
