# Generated by Django 3.1.2 on 2020-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0036_auto_20201006_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
