# Generated by Django 3.1.2 on 2020-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0040_auto_20201218_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
