# Generated by Django 3.1.2 on 2020-12-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0049_auto_20201218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
