# Generated by Django 3.1.2 on 2021-01-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0050_auto_20201218_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['Lname']},
        ),
        migrations.RemoveField(
            model_name='activesales',
            name='deliverydate',
        ),
        migrations.AddField(
            model_name='activesales',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
