# Generated by Django 3.1.5 on 2021-03-05 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0053_auto_20210214_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 3, 13, 16, 17, 8, 114759)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingtime',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 10, 0)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='batch',
            field=models.CharField(default='BATCH_', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='end_sales',
            field=models.DateField(default=datetime.datetime(2021, 3, 11, 16, 17, 8, 114759)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='start_sales',
            field=models.DateField(default=datetime.datetime(2021, 3, 8, 16, 17, 8, 114759)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='units',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
