# Generated by Django 3.1.2 on 2021-02-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0054_auto_20210214_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='units',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
