# Generated by Django 3.1.5 on 2021-06-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0054_auto_20210304_1617'),
        ('MainPage', '0055_auto_20210214_1258'),
    ]

    operations = [
    ]
