# Generated by Django 3.1.5 on 2021-06-08 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0059_auto_20210608_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('index', 'index'), ('About Us', 'About Us'), ('Sanitation Protocols', 'Sanitation'), ('Licenses', 'Licenses'), ('Projects', 'Projects')], max_length=35)),
                ('subtitle', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 14, 10, 43, 240505)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
