# Generated by Django 3.1.5 on 2021-06-08 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0061_auto_20210608_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 14, 29, 29, 549092)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
