# Generated by Django 3.1.5 on 2021-10-11 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0063_auto_20210712_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='Dog_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activesales',
            name='EvMix_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 23, 14, 38, 34, 640948)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
