# Generated by Django 3.1.5 on 2021-10-11 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0064_auto_20211011_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Dog_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='EvMix_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 23, 14, 48, 35, 677837)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
