# Generated by Django 3.1.5 on 2021-10-22 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0065_auto_20211011_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randombakeitem',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='orders',
            name='recipient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 10, 46, 49, 664557)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingtime',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 10, 15)),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='units',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='randombakeitem',
            name='photo',
            field=models.ImageField(upload_to='RandomBake_images'),
        ),
    ]
