# Generated by Django 3.1.5 on 2021-10-22 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0066_auto_20211022_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 10, 51, 53, 689538)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='recipient',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
