# Generated by Django 3.1.5 on 2021-10-22 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0067_auto_20211022_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='AButter_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 11, 37, 35, 95318)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
