# Generated by Django 3.1.5 on 2021-10-22 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0068_auto_20211022_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ticket_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 11, 38, 43, 216827)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
