# Generated by Django 3.1.5 on 2021-10-22 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0069_auto_20211022_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 15, 53, 29, 705299)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
