# Generated by Django 3.1.5 on 2021-10-24 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0070_auto_20211022_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesales',
            name='AButter_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 11, 18, 6, 504897)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivorder',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
