# Generated by Django 3.1.5 on 2021-10-24 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0071_auto_20211024_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesales',
            name='bakingdate',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 11, 42, 56, 753225)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ticket_text',
            field=models.TextField(blank=True),
        ),
    ]
