# Generated by Django 3.1 on 2020-09-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=264)),
                ('pref_brand', models.CharField(max_length=264)),
                ('ingredient_long', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='fermIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferm_ingrd_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ferm_ingred_metric', models.TextField(choices=[('g', 'Grams'), ('Kg', 'Kilogram'), ('mL', 'milliliters'), ('Oz', 'Ounces'), ('Lb', 'Pounds'), ('Tbs', 'Tablespoon'), ('Tsp', 'Teaspoon'), ('Cup', 'Cup')], max_length=40)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.ingredient')),
            ],
        ),
    ]
