# Generated by Django 3.1.2 on 2020-12-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fermIngredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
