# Generated by Django 3.1 on 2020-09-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_baking_batch_preferment'),
    ]

    operations = [
        migrations.CreateModel(
            name='doughIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough_ingrd_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dough_ingred_metric', models.TextField(choices=[('g', 'Grams'), ('Kg', 'Kilogram'), ('mL', 'milliliters'), ('Oz', 'Ounces'), ('Lb', 'Pounds'), ('Tbs', 'Tablespoon'), ('Tsp', 'Teaspoon'), ('Cup', 'Cup')], max_length=40)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough_mixed_minutes', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_mixer_speed', models.PositiveIntegerField()),
                ('dough_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_final_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_mixer_spring', models.PositiveIntegerField()),
                ('knead_start_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('knead_finish_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dough_final_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dough_photo', models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images')),
                ('kneading_photo', models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images')),
                ('dough_notes', models.TextField(default='None')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.baking_batch')),
                ('dough_ingredients', models.ManyToManyField(to='Recipes.doughIngredients')),
            ],
        ),
    ]
