# Generated by Django 3.1 on 2020-09-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_dough_doughingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapingFinishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_each_item', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items_produced', models.PositiveIntegerField()),
                ('retard_started', models.TimeField()),
                ('retard_finished', models.TimeField()),
                ('shape_photo', models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images')),
                ('preform_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('postform_rest_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('boil_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('oven_first_temp', models.PositiveIntegerField()),
                ('oven_first_time', models.PositiveIntegerField()),
                ('oven_second_temp', models.PositiveIntegerField()),
                ('oven_second_time', models.PositiveIntegerField()),
                ('steam_used', models.BooleanField()),
                ('steam_time', models.PositiveIntegerField()),
                ('baked_photo', models.ImageField(default='/media/photo-placeholder-icon.jpg', upload_to='batch_images')),
                ('shaping_finishing_notes', models.TextField(default='None')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.baking_batch')),
            ],
        ),
    ]
