# Generated by Django 3.1 on 2020-09-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_shapingfinishing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doughingredients',
            old_name='ingredient',
            new_name='dough_ingredient',
        ),
        migrations.RenameField(
            model_name='fermingredients',
            old_name='ingredient',
            new_name='ferm_ingredient',
        ),
    ]
