# Generated by Django 3.1 on 2020-09-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_auto_20200921_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baking_batch',
            name='room_humid',
            field=models.DecimalField(decimal_places=1, default=50, max_digits=4),
        ),
        migrations.AlterField(
            model_name='baking_batch',
            name='room_temp',
            field=models.DecimalField(decimal_places=1, default=75.0, max_digits=4),
        ),
    ]
